user_api:
    type: annotation
    resource: "@ApiBundle/Controller/UserController.php"
    prefix: /user

field_activities_api:
    type: annotation
    resource: "@ApiBundle/Controller/FieldActivityController.php"
    prefix: /field-activity

answers_api:
    type: annotation
    resource: "@ApiBundle/Controller/AnswerController.php"
    prefix: /answer

logs_api:
    type: annotation
    resource: "@ApiBundle/Controller/LogController.php"
    prefix: /log

util_api:
    type: annotation
    resource: "@ApiBundle/Controller/UtilsController.php"
    prefix: /util

media_api:
    type: annotation
    resource: "@ApiBundle/Controller/MediaController.php"
    prefix: /media

notifications_api:
    type: annotation
    resource: "@ApiBundle/Controller/NotificationController.php"
    prefix: /notifications

