services:
  email.services:
    class: AppBundle\Services\EmailService
    arguments: ["@swiftmailer.mailer","@templating","%contactMail%","%projectName%", "@service_container"]

  notification_push.services:
    class: AppBundle\Services\FirebaseService
    arguments: [ "@doctrine.orm.entity_manager"]

  app.admin.school:
    class: AppBundle\Admin\SchoolAdmin
    arguments: [~, AppBundle\Entity\School, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: School }
    public: true
