services:
  email.services:
    class: AppBundle\Services\EmailService
    arguments: ["@swiftmailer.mailer","@templating","%contactMail%","%projectName%", "@service_container"]

  notification_push.services:
    class: AppBundle\Services\FirebaseService
    arguments: [ "@doctrine.orm.entity_manager"]

  app.admin.school:
    class: AppBundle\Admin\SchoolAdmin
    arguments: [~, AppBundle\Entity\School, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: School }
    public: true

  app.admin.fieldactivities:
    class: AppBundle\Admin\FieldAdmin
    arguments: [~, AppBundle\Entity\FieldActivity, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: Field activities }
    public: true

  app.admin.task:
    class: AppBundle\Admin\TaskAdmin
    arguments: [~, AppBundle\Entity\Task, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: Tasks }
    public: true

  app.admin.answer:
    class: AppBundle\Admin\AnswerAdmin
    arguments: [~, AppBundle\Entity\Answer, Sonata\AdminBundle\Controller\CRUDController]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: Answers }
    public: true
